### ISSUE TITLE
perfSONAR role

### ISSUE THREAD

**Issue by EliciaHeera** [AAROC/perfsonar-base#7]
How do you apply the playbook to selected nodes?

**Comment by brucellino** [comment]
The selected nodes are defined in the [Inventory](http://docs.ansible.com/ansible/latest/intro_inventory.html). You define groups and members there, and use those group names in your playbook. 

E.g. : 

```
[mesh]
monitor1.domain
monitor2.domain
monitor3.domain
[central]
central-node.domain
```

The playbook can apply roles to all hosts in a group by using the group name : 

```
# example playbook
- hosts: all
  roles:
  - perfsonar-base

- hosts: central
  roles: 
    - perfsonar-central
```
